
plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.example.botapk'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.botapk"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            pip {
                install "requests"
                install "numpy"
                install "websocket-client"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            python.srcDir "src/main/python"
        }
    }
}

dependencies {}
